{
 "title": "Otus_DZ_05",
 "description": "Графики для ДЗ Отус\nСделать дашборд в Графане, в котором были бы метрики с разбивкой по API методам:\n1.\tLatency (response time) с квантилями по 0.5, 0.95, 0.99, max\n2.\tRPS\n3.\tError Rate - количество 500ых ответов\n\nДобавить в дашборд графики с метрикам в целом по сервису, взятые с nginx-ingress-controller:\n1.\tLatency (response time) с квантилями по 0.5, 0.95, 0.99, max\n2.\tRPS\n3.\tError Rate - количество 500ых ответов\n",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Igress CrudApi Latency QMax",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(1.0, sum by(le)(rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"crud-api-service\"}[2m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress CrudApi Latency Q0.99",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"crud-api-service\"}[2m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress CrudApi Latency Q0.95",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"crud-api-service\"}[2m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingres CrudApi  Latency  Q0.5",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"crud-api-service\"}[2m]))  by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress CrudApi Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_bucket{http_route=~\"/delay.+\", http_response_status_code=~\"5..\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress CrudApi RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_service=\"crud-api-service\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Crud API latency по методам",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency q 0.5",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le, http_route, http_request_method) (rate(http_server_request_duration_seconds_bucket{http_route=~\"/delay.+\", http_request_method=\"GET\", service=\"crud-api-service\"}[2m])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latency  q0.95",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, http_route, http_request_method) (rate(http_server_request_duration_seconds_bucket{http_route=~\"/delay.+\", http_request_method=\"GET\", service=\"crud-api-service\"}[2m])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latency q0.99",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, http_route, http_request_method) (rate(http_server_request_duration_seconds_bucket{http_route=~\"/delay.+\", http_request_method=\"GET\", service=\"crud-api-service\"}[2m])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latency Q Max",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 },
     "targets": [
      {
       "expr": "histogram_quantile(1.0, sum by(le, http_route, http_request_method) (rate(http_server_request_duration_seconds_bucket{http_route=~\"/delay.+\", http_request_method=\"GET\", service=\"crud-api-service\"}[2m])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CrudApi RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "sum(rate(http_server_request_duration_seconds_bucket{http_route=~\"/delay.+\", http_request_method=\"GET\"}[2m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CrudApi  Error rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "sum(rate(http_server_request_duration_seconds_bucket{http_route=~\"/delay.+\", http_response_status_code=~\"5..\"}[2m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}