{
 "title": "ApiGateway",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Максимум (квантиль 1.0)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(1.0, sum by (le, http_route) (rate(http_server_request_duration_seconds_bucket{http_route=\"/api/customers/auth/{**catch-all}\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Квантиль 0.99",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, http_route) (rate(http_server_request_duration_seconds_bucket{http_route=\"/api/customers/auth/{**catch-all}\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Квантиль 0.95",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, http_route) (rate(http_server_request_duration_seconds_bucket{http_route=\"/api/customers/auth/{**catch-all}\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Квантиль 0.5 (медиана)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le, http_route) (rate(http_server_request_duration_seconds_bucket{http_route=\"/api/customers/auth/{**catch-all}\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate (500-е ответы)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (http_route) (rate(http_server_request_duration_seconds_count{http_route=\"/api/customers/auth/{**catch-all}\", http_response_status_code=\"500\"}[1m]))",
     "legendFormat": "Error Rate (500) {{http_route}}"
    }
   ]
  },
  {
   "title": "RPS (Requests Per Second)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 6 },
   "targets": [
    {
     "expr": "sum by (http_route) (rate(http_server_request_duration_seconds_count{http_route=\"/api/customers/auth/{**catch-all}\"}[1m]))",
     "legendFormat": "RPS {{http_route}}"
    }
   ]
  }
 ]
}