apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config-orders
  namespace: myns
data:
  CONNECTION_STRING: "Host=pg16-postgresql;Database=orders;Username=postgres;Password=postgres"
  RABBIT: "amqp://me:userPass@rabbit-rabbitmq:5672/"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
  namespace: myns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      containers:
      - name: orders-service
        image: monguard2/otus_dz_8_orders_api:1.0
        ports:
        - containerPort: 80
        env:
        - name: ConnectionStrings__ordersdb
          valueFrom:
            configMapKeyRef:
              name: db-config-orders
              key: CONNECTION_STRING
        - name: ConnectionStrings__rabbitmq
          valueFrom:
            configMapKeyRef:
              name: db-config-orders
              key: RABBIT                
---

apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: myns
spec:
  selector:
    app: orders-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config-payments
  namespace: myns  
data:
  CONNECTION_STRING: "Host=pg16-postgresql;Database=payments;Username=postgres;Password=postgres"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-service
  namespace: myns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-service
  template:
    metadata:
      labels:
        app: payments-service
    spec:
      containers:
      - name: payments-service
        image: monguard2/otus_dz_8_payments_api:1.0
        ports:
        - containerPort: 80
        env:
        - name: ConnectionStrings__paymentsdb
          valueFrom:
            configMapKeyRef:
              name: db-config-payments
              key: CONNECTION_STRING
        - name: ConnectionStrings__rabbitmq
          valueFrom:
            configMapKeyRef:
              name: db-config-orders
              key: RABBIT  
---
apiVersion: v1
kind: Service
metadata:
  name: payments-service
  namespace: myns
spec:
  selector:
    app: payments-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config-stocks
  namespace: myns
data:
  CONNECTION_STRING: "Host=pg16-postgresql;Database=stocks;Username=postgres;Password=postgres"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: stocks-service
  namespace: myns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stocks-service
  template:
    metadata:
      labels:
        app: stocks-service
    spec:
      containers:
      - name: stocks-service
        image: monguard2/otus_dz_8_stocks_api:1.0
        ports:
        - containerPort: 80
        env:
        - name: ConnectionStrings__stocksdb
          valueFrom:
            configMapKeyRef:
              name: db-config-stocks
              key: CONNECTION_STRING
        - name: ConnectionStrings__rabbitmq
          valueFrom:
            configMapKeyRef:
              name: db-config-orders
              key: RABBIT  
---
apiVersion: v1
kind: Service
metadata:
  name: stocks-service
  namespace: myns
spec:
  selector:
    app: stocks-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---

### Delivery

apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config-delivery
  namespace: myns
data:
  CONNECTION_STRING: "Host=pg16-postgresql;Database=delivery;Username=postgres;Password=postgres"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service
  namespace: myns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-service
  template:
    metadata:
      labels:
        app: delivery-service
    spec:
      containers:
      - name: delivery-service
        image: monguard2/otus_dz_8_delivery_api:1.0
        ports:
        - containerPort: 80
        env:
        - name: ConnectionStrings__deliverydb
          valueFrom:
            configMapKeyRef:
              name: db-config-delivery
              key: CONNECTION_STRING
        - name: ConnectionStrings__rabbitmq
          valueFrom:
            configMapKeyRef:
              name: db-config-orders
              key: RABBIT
---
apiVersion: v1
kind: Service
metadata:
  name: delivery-service
  namespace: myns
spec:
  selector:
    app: delivery-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
