apiVersion: v1
kind: Service
metadata:
  name: {{ include "crud-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ include "crud-api.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}