kubectl create ns myns
kubectl apply -f api-gateway.yaml
kubectl apply -f cart.yaml
kubectl apply -f catalog.yaml
kubectl apply -f customer.yaml
kubectl apply -f notification.yaml
kubectl apply -f orders.yaml
kubectl apply -f stubs.yaml
kubectl apply -f ingress.yaml